version: '3.8'

services:
  mariadb:
    container_name: mariadb              # Le nom du container
    build:
      context: requirements/mariadb     # Chemin vers le Dockerfile
      dockerfile: Dockerfile            # Nom du Dockerfile (optionnel si c'est "Dockerfile")
    env_file: .env                       # Fichier contenant les variables d'environnement
    volumes:                             # Volume persistant pour MariaDB
      - mariadb:/var/lib/mysql
    restart: unless-stopped             # Redémarrage automatique sauf si explicitement arrêté
    expose:
      - "3306"                           # Expose le port à d'autres services dans le réseau Docker
    networks:
      - inception                        # Réseau Docker dédié

  nginx:
    container_name: nginx
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
    restart: on-failure   # Ici nous changeons, le container redémarrera uniquement en cas de crash.
    ports:
      - "443:443"        # on indique le port qui sera exposé a la machine locale
    networks:
      - inception
    depends_on:           # Nouvelle ligne, indiquant de ne pas démarrer NGINX tant que WordPress n'a pas démarré.
      - wordpress

  wordpress:
    container_name: wordpress
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress       # Partage du volume avec nginx
    restart: on-failure
    networks:
      - inception
    depends_on:                            # WordPress attend que MariaDB soit démarré
      - mariadb
    expose:
     - "9000"                            # Expose le port 9000 pour PHP-FPM (interne au réseau Docker)

networks:
  inception:
    driver: bridge

volumes:
  wordpress:
    driver: local                       # ici nous stockons le volume en local
    driver_opts:
      type: 'none'                      # aucun type spécifique
      o: 'bind'
      device: '/home/vboxuser/data/wordpress' #Ou stocker le dossier sur votre ordinateur en local
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'    # Les Bind Mounts sont des volumes qui se montent sur un chemin d'accès à l'hôte, et ils peuvent être modifiés par d'autres processus en dehors de docker.
      device: '/home/vboxuser/data/mariadb'  #Ou stocker le dossier sur votre ordinateur en local
