; ==============================================
; Configuration de PHP-FPM pour WordPress
; PHP-FPM = le moteur qui exécute le code PHP
; ==============================================

; Nom du "pool" de processus (juste un identifiant)
[www]

; Sous quel utilisateur tourne PHP-FPM
user = nobody
group = nobody

; IMPORTANT : on écoute sur le port 9000 de TOUTES les interfaces
; (comme bind-address = 0.0.0.0 pour MariaDB)
; NGINX (dans un autre conteneur) enverra les requêtes PHP ici
listen = 0.0.0.0:9000

; Gestion des processus PHP
; "dynamic" = PHP-FPM ajuste le nombre de processus selon la charge
pm = dynamic

; Maximum 5 processus PHP en parallèle
pm.max_children = 5

; 2 processus démarrés au lancement
pm.start_servers = 2

; Minimum 1 processus en attente
pm.min_spare_servers = 1

; Maximum 3 processus en attente
pm.max_spare_servers = 3